import Head from "next/head";
import useAuth from "../hooks/useAuth";
import Playlists from "../components/playlists";

export default function Home() {
  const res = useAuth();

  const getUsername = () => {
    if (res.user) {
      return res.user.username;
    }
    return undefined;
  };

  const getUserId = () => {
    if (res.user) {
      return res.user.id;
    }
    return undefined;
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full">
        <Playlists
          isLoggedIn={res.isLoggedIn}
          username={getUsername()}
          id={getUserId()}
        />
      </main>
    </>
  );
}
