import Head from "next/head";
import { useState, useEffect } from "react";
import Link from "next/link";
import useAuth from "../hooks/useAuth";
import Playlists from "../components/playlists";

export default function Home() {
  const res = useAuth();
  const [loggedIn, setLoggedIn] = useState(res.isLoggedIn);

  useEffect(() => {
    setLoggedIn(res.isLoggedIn);
  });

  const getUsername = () => {
    if (res.user) {
      return res.user.username;
    }
    return undefined;
  };

  const getUserId = () => {
    if (res.user) {
      return res.user.id;
    }
    return undefined;
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full">
        {loggedIn ? (
          <Playlists
            isLoggedIn={res.isLoggedIn}
            username={getUsername()}
            id={getUserId()}
          />
        ) : (
          <div className="fixed flex justify-center items-center w-full h-full">
            <Link href="/login" className="font-bold text-[#e65722]">
              Login
            </Link>{" "}
            &nbsp;or{" "}
            <Link href="/signup" className="font-bold text-[#e65722]">
              &nbsp;Signup
            </Link>
            &nbsp;to create playlists
          </div>
        )}
      </main>
    </>
  );
}
